apiVersion: v1
kind: Service
metadata:
  labels:
    name: console
  name: twistlock-console
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.serviceClusterIP }}
  clusterIP: {{ .Values.serviceClusterIP }}
  {{- else}}{{- end}}
  ports:
  - name: communication-port
    port: {{ .Values.COMMUNICATION_PORT }}
  - name: management-port-https
    port: {{ .Values.MANAGEMENT_PORT_HTTPS }}
  {{- if .Values.MANAGEMENT_PORT_HTTP }}
  - name: mgmt-http
    port: {{ .Values.MANAGEMENT_PORT_HTTP }}
  {{- else }}
  {{- end}}
  selector:
    name: twistlock-console
  type: {{ .Values.serviceType }}