# CircleCI sample file for Twistlock CI integration
#

version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/app
    
# In this example, we're using a CircleCI context (https://circleci.com/docs/2.0/contexts/)
# to store the username & password of our Twistlock CI user account
# and the URL to our console. The context is named "tl_scan_context"
# and contains the following variables:

# TL_USER:  The Twistlock user with the CI User role
# TL_PASS:  The password for this user account
# TL_CONSOLE_URL:  The base URL for the console -- http://console.<my_company>.com:8083 -- without a trailing /

    steps:
      # Run the built-in checkout script to checkout the code in this repo
      - checkout
      # Download twistcli from the configured Twistlock console
      - run: curl -k -u $TL_USER:$TL_PASS --output ~/app/twistcli $TL_CONSOLE_URL/api/v1/util/twistcli
      # ...and ensure it's executable.
      - run: sudo chmod a+x ./twistcli
      
      # Build our project that is contained in the code
      # checked out above.
      - run: docker build -t corp/helloworld:$CIRCLE_BRANCH .
      
      # Run the scan with twistcli, providing detailed results in CircleCI and
      # pushing the results to the Twistlock console.
      # --details returns all vulnerabilities & compliance issues rather than just summaries.
      # -address points to our Twistlock console
      # -u and -p provide credentials for the console.  These creds only need the CI User role.
      # Finally, we provide the name of the image we built with 'docker build', above.
      - run: ./twistcli images scan --details -address $TL_CONSOLE_URL -u $TL_USER -p $TL_PASS corp/helloworld:$CIRCLE_BRANCH
      # Add --vulnerability-threshold and/or --compliance-threshold to this command to
      # fail builds based on the thresholds.
      # See twistcli documentation for more details.
  # add any additional commands needed to test the image, push to a registry, etc.

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
         context: tl_scan_context
